# Generated by Django 3.2.8 on 2021-11-17 22:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('cell_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email_address', models.EmailField(max_length=150, null=True)),
                ('child_name', models.CharField(max_length=150, null=True)),
                ('child_age', models.CharField(max_length=5, null=True)),
                ('school_name', models.CharField(max_length=150, null=True)),
                ('child_grade', models.CharField(max_length=5, null=True)),
                ('preferred_date', models.DateField(null=True)),
                ('time_choices', models.CharField(max_length=5, null=True)),
                ('contact_choices', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
