# Generated by Django 3.2.8 on 2021-11-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='title',
        ),
    ]
