# Generated by Django 3.2.8 on 2021-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contactlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
